name: Build and Deploy a Production

on:
  push:
    branches: [ main ] # Se ejecuta cuando haces push a main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de tu código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar sitio Astro
        run: npm run build

      - name: Subir HTML a la rama production
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: production
          publish_dir: ./dist 